# Generated by Django 5.1.1 on 2024-10-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "idCategoria",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="idCategoria",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Gastos",
            fields=[
                (
                    "idGastos",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="idGastos",
                    ),
                ),
                ("categoria", models.CharField(max_length=50)),
                ("retirado_em", models.DateField(auto_now_add=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="Receitas",
            fields=[
                (
                    "idReceitas",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="idReceitas",
                    ),
                ),
                ("categoria", models.CharField(max_length=50)),
                ("adicionado_em", models.DateField(auto_now_add=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
