# Generated by Django 5.1.2 on 2024-10-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
                ('retirado_em', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
                ('adicionado_em', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
