# Generated by Django 5.1.2 on 2024-11-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='retirado_em',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='adicionado_em',
            field=models.DateField(),
        ),
    ]
