# Generated by Django 5.1.2 on 2024-11-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_alter_gastos_retirado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitcoin',
            fields=[
                ('idReceitas', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idBitcoin')),
                ('adicionado_em', models.DateField()),
                ('valor', models.DecimalField(decimal_places=15, max_digits=20)),
            ],
        ),
    ]
